name: "pr-comment-file-size"
description: "Comments file sizes on a given PR"
author: "sarthak-saxena & fatton139"
inputs:
  dist_path:
    description: "output path for the build package"
    required: true
    default: "dist"
  token:
    description: "your GITHUB_TOKEN"
    required: true
  update_comment:
    description: "whether to update the existing comment or create new ones"
    required: false
    default: true
runs:
  using: "node12"
  main: "dist/index.js"
outputs:
  size: # output will be available to future steps
    description: "Build Size"
branding:
  icon: "hard-drive"
  color: "blue"
