name: "pr-comment-file-size"
description: "Analyses and compares file sizes then comments them onto the current PR."
author: "fatton139"
inputs:
  path:
    description: "Path to file or directory for file sizes analysis."
    required: true
  diff_path:
    description: "Optional path to another directory to perform file size diff against the provided path."
    required: false
  token:
    description: "your GITHUB_TOKEN env var."
    required: true
  update_comment:
    description: "whether to update the existing comment or create new ones on each run."
    required: false
    default: true
runs:
  using: "node12"
  main: "dist/index.js"
outputs:
  size: # output will be available to future steps
    description: "Build Size"
branding:
  icon: "hard-drive"
  color: "blue"
