name: CI

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

permissions:
  contents: read
  pull-requests: write

jobs:
  calculate-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./
        with:
          path: ${{ github.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}
