name: Test action - file with no diff

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./
        with:
          path: ${{ github.workspace }}/dist/index.js
          token: ${{ secrets.GITHUB_TOKEN }}
