name: Test action - File glob pattern

on:
  push:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./
        with:
          path: ${{ github.workspace }}
          update_comment: false
          token: ${{ secrets.GITHUB_TOKEN }}
          file_glob_pattern: "*.json"
